"use client";
import { QueryClient, QueryClientProvider } from "react-query";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import { ReactQueryDevtools } from "react-query/devtools";
import { Metadata } from "next";
import Head from "next/head";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const queryClient = new QueryClient();

  return (
    <html lang="en">
      <body className="bg-dark">
        <QueryClientProvider client={queryClient}>
          {children}
          <ToastContainer
              position="bottom-right"
              autoClose={5000}
              hideProgressBar
              newestOnTop={false}
              closeOnClick
              rtl
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="dark"
            />
          <ReactQueryDevtools />
        </QueryClientProvider>
      </body>
    </html>
  );
}
